-- Initial schema migration for Template API
-- This migration is intended to provide a baseline schema for production.

CREATE TABLE tb_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,

    name       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,

    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL
);

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tb_role (id)
);

CREATE TABLE tb_person
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,

    name       VARCHAR(255) NOT NULL,
    birth_date DATE,
    user_id    BIGINT       NOT NULL UNIQUE,
    CONSTRAINT fk_person_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_document
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,

    type       VARCHAR(255) NOT NULL,
    number     VARCHAR(255) NOT NULL,
    person_id  BIGINT       NOT NULL,
    CONSTRAINT fk_document_person FOREIGN KEY (person_id) REFERENCES tb_person (id)
);

CREATE TABLE tb_contact_type
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,

    name       VARCHAR(255) NOT NULL UNIQUE,
    icon_url   VARCHAR(255)
);

CREATE TABLE tb_contact
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    deleted_at      TIMESTAMP,

    value           VARCHAR(255) NOT NULL,
    contact_type_id BIGINT       NOT NULL,
    person_id       BIGINT       NOT NULL,
    CONSTRAINT fk_contact_type FOREIGN KEY (contact_type_id) REFERENCES tb_contact_type (id),
    CONSTRAINT fk_contact_person FOREIGN KEY (person_id) REFERENCES tb_person (id)
);

CREATE TABLE audit_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    action     VARCHAR(255) NOT NULL,
    principal  VARCHAR(255),
    details    VARCHAR(2000)
);

CREATE TABLE user_growth_snapshot
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    deleted_at    TIMESTAMP,

    snapshot_date DATE   NOT NULL,
    user_count    BIGINT NOT NULL
);

CREATE INDEX idx_user_username ON tb_user (username);
CREATE INDEX idx_user_email ON tb_user (email);
CREATE INDEX idx_user_deleted_at ON tb_user (deleted_at);
CREATE INDEX idx_role_deleted_at ON tb_role (deleted_at);
CREATE INDEX idx_person_user_id ON tb_person (user_id);
CREATE INDEX idx_person_deleted_at ON tb_person (deleted_at);
CREATE INDEX idx_document_person_id ON tb_document (person_id);
CREATE INDEX idx_document_deleted_at ON tb_document (deleted_at);
CREATE INDEX idx_contact_type_deleted_at ON tb_contact_type (deleted_at);
CREATE INDEX idx_contact_contact_type_id ON tb_contact (contact_type_id);
CREATE INDEX idx_contact_person_id ON tb_contact (person_id);
CREATE INDEX idx_contact_deleted_at ON tb_contact (deleted_at);
CREATE INDEX idx_user_growth_snapshot_date ON user_growth_snapshot (snapshot_date);
CREATE UNIQUE INDEX idx_growth_snapshot_date_active
    ON user_growth_snapshot (snapshot_date) WHERE deleted_at IS NULL;
CREATE INDEX idx_audit_log_action ON audit_log (action);
CREATE INDEX idx_audit_log_principal ON audit_log (principal);
CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);
